export const translations = {
  en: {
    site_name: "NoFiador.com",
    site_slogan: "Your home in Medellin, without a co-signer.",
    browse_properties: "Browse Properties",
    list_property: "List a Property",
    language: "Language",
    price_per_month: "/month",
    bedrooms: "Bedrooms",
    bathrooms: "Bathrooms",
    area: "m²",
    view_details: "View Details",
    contact_landlord: "Contact Landlord",
    close: "Close",
    usp_title: "Rent without a 'fiador'",
    usp_description: "We exclusively list properties from landlords who welcome foreigners and locals without requiring a co-signer, making your move to Medellin smoother.",
    list_your_property_title: "List Your Property with NoFiador.com",
    list_your_property_subtitle: "Reach thousands of foreigners and locals looking for a home in Medellin. No co-signer required for tenants means more potential renters for you.",
    listing_fee: "One-time listing fee: $9.99 USD",
    pay_with_paypal: "Pay with PayPal",
    payment_success_title: "Payment Successful!",
    payment_success_message: "Your property is now listed on NoFiador.com. You will be contacted by interested tenants directly.",
    back_to_browsing: "Back to Browsing",
    all_rights_reserved: "All rights reserved.",
    login: "Log In",
    signup: "Sign Up",
    logout: "Log Out",
    profile: "Profile",
    email: "Email",
    password: "Password",
    landlord: "Landlord",
    renter: "Renter",
    i_am_a: "I am a...",
    login_to_account: "Log in to your account",
    create_account: "Create an account",
    dont_have_account: "Don't have an account?",
    already_have_account: "Already have an account?",
    login_failed: "Login failed. Please check your credentials.",
    signup_failed: "An account with this email already exists.",
    my_listings: "My Listings",
    my_saved_properties: "My Saved Properties",
    welcome_back: "Welcome back",
    no_listings_yet: "You haven't listed any properties yet.",
    no_saved_properties: "You haven't saved any properties yet. Click the heart icon on a listing to save it!",
    save: "Save",
    saved: "Saved",
    login_to_list: "Please log in as a landlord to list a property.",
    filter_by_neighborhood: "Filter by neighborhood",
    all_neighborhoods: "All Neighborhoods",
    sort_by_price: "Sort by price",
    price_low_to_high: "Price: Low to High",
    price_high_to_low: "Price: High to Low",
    next_step: "Next Step",
    back_step: "Back",
    publish_listing: "Publish Listing",
    update_listing: "Update Listing",
    step_1_title: "Step 1: Basic Information",
    step_2_title: "Step 2: Property Details",
    step_3_title: "Step 3: Photos",
    step_4_title: "Step 4: Review & Pay",
    title_en: "Title (English)",
    title_es: "Title (Spanish)",
    price_cpo: "Price (COP)",
    neighborhood: "Neighborhood",
    select_neighborhood: "Select a neighborhood",
    description_en: "Description (English)",
    description_es: "Description (Spanish)",
    photo_urls: "Photo URLs",
    photo_urls_placeholder: "Paste image URLs, separated by commas",
    photo_preview: "Photo Preview",
    edit: "Edit",
    delete: "Delete",
    delete_confirm_title: "Are you sure?",
    delete_confirm_message: "Are you sure you want to delete this listing? This action cannot be undone.",
    cancel: "Cancel",
    confirm_delete: "Yes, Delete",
    editing_property: "Editing Property",
    creating_property: "Creating New Property",
    create_account_to_message: "Create an account to send a message",
    signup_to_message: "Sign Up to Message",
    view_full_page: "View Full Page",
    edit_profile: "Edit Profile",
    settings: "Settings",
    contact_name: "Contact Name",
    contact_phone: "Contact Phone",
    save_changes: "Save Changes",
    profile_updated: "Profile updated successfully!",
    profile_update_error: "Failed to update profile.",
  },
  es: {
    site_name: "NoFiador.com",
    site_slogan: "Tu hogar en Medellín, sin fiador.",
    browse_properties: "Ver Propiedades",
    list_property: "Publicar Propiedad",
    language: "Idioma",
    price_per_month: "/mes",
    bedrooms: "Habitaciones",
    bathrooms: "Baños",
    area: "m²",
    view_details: "Ver Detalles",
    contact_landlord: "Contactar al Propietario",
    close: "Cerrar",
    usp_title: "Alquila sin fiador",
    usp_description: "Listamos exclusivamente propiedades de arrendadores que aceptan extranjeros y locales sin requerir un fiador, facilitando tu mudanza a Medellín.",
    list_your_property_title: "Publica Tu Propiedad en NoFiador.com",
    list_your_property_subtitle: "Llega a miles de extranjeros y locales que buscan un hogar en Medellín. No requerir fiador para los inquilinos significa más potenciales arrendatarios para ti.",
    listing_fee: "Tarifa única por publicación: $9.99 USD",
    pay_with_paypal: "Pagar con PayPal",
    payment_success_title: "¡Pago Exitoso!",
    payment_success_message: "Tu propiedad ha sido publicada en NoFiador.com. Los inquilinos interesados se pondrán en contacto contigo directamente.",
    back_to_browsing: "Volver a Explorar",
    all_rights_reserved: "Todos los derechos reservados.",
    login: "Iniciar Sesión",
    signup: "Registrarse",
    logout: "Cerrar Sesión",
    profile: "Perfil",
    email: "Correo Electrónico",
    password: "Contraseña",
    landlord: "Arrendador",
    renter: "Inquilino",
    i_am_a: "Soy un...",
    login_to_account: "Inicia sesión en tu cuenta",
    create_account: "Crea una cuenta",
    dont_have_account: "¿No tienes una cuenta?",
    already_have_account: "¿Ya tienes una cuenta?",
    login_failed: "Error de inicio de sesión. Por favor, verifica tus credenciales.",
    signup_failed: "Ya existe una cuenta con este correo electrónico.",
    my_listings: "Mis Propiedades",
    my_saved_properties: "Mis Propiedades Guardadas",
    welcome_back: "Bienvenido/a de nuevo",
    no_listings_yet: "Aún no has publicado ninguna propiedad.",
    no_saved_properties: "¡No has guardado ninguna propiedad todavía! Haz clic en el icono del corazón en una publicación para guardarla.",
    save: "Guardar",
    saved: "Guardado",
    login_to_list: "Por favor, inicia sesión como arrendador para publicar una propiedad.",
    filter_by_neighborhood: "Filtrar por barrio",
    all_neighborhoods: "Todos los Barrios",
    sort_by_price: "Ordenar por precio",
    price_low_to_high: "Precio: Menor a Mayor",
    price_high_to_low: "Precio: Mayor a Menor",
    next_step: "Siguiente Paso",
    back_step: "Atrás",
    publish_listing: "Publicar Propiedad",
    update_listing: "Actualizar Propiedad",
    step_1_title: "Paso 1: Información Básica",
    step_2_title: "Paso 2: Detalles de la Propiedad",
    step_3_title: "Paso 3: Fotos",
    step_4_title: "Paso 4: Revisar y Pagar",
    title_en: "Título (Inglés)",
    title_es: "Título (Español)",
    price_cpo: "Precio (COP)",
    neighborhood: "Barrio",
    select_neighborhood: "Selecciona un barrio",
    description_en: "Descripción (Inglés)",
    description_es: "Descripción (Español)",
    photo_urls: "URLs de las Fotos",
    photo_urls_placeholder: "Pega las URLs de las imágenes, separadas por comas",
    photo_preview: "Vista Previa de Fotos",
    edit: "Editar",
    delete: "Eliminar",
    delete_confirm_title: "¿Estás seguro?",
    delete_confirm_message: "¿Estás seguro de que quieres eliminar esta propiedad? Esta acción no se puede deshacer.",
    cancel: "Cancelar",
    confirm_delete: "Sí, Eliminar",
    editing_property: "Editando Propiedad",
    creating_property: "Creando Nueva Propiedad",
    create_account_to_message: "Crea una cuenta para enviar un mensaje",
    signup_to_message: "Regístrate para Enviar Mensaje",
    view_full_page: "Ver Página Completa",
    edit_profile: "Editar Perfil",
    settings: "Configuración",
    contact_name: "Nombre de Contacto",
    contact_phone: "Teléfono de Contacto",
    save_changes: "Guardar Cambios",
    profile_updated: "¡Perfil actualizado con éxito!",
    profile_update_error: "Error al actualizar el perfil.",
  },
};

export const neighborhoods = [
  "Belen",
  "Buenos Aires",
  "El Carmen",
  "El Poblado",
  "El Retiro",
  "Envigado",
  "Itagui",
  "Laureles",
  "Manila",
  "Palmas",
  "Rionegro",
  "Sabaneta",
].sort();
