export const translations = {
  en: {
    site_name: "NoFiador.com",
    site_slogan: "Your home in Medellin, without a co-signer.",
    browse_properties: "Browse Properties",
    list_property: "List a Property",
    language: "Language",
    price_per_month: "/month",
    bedrooms: "Bedrooms",
    bathrooms: "Bathrooms",
    area: "m²",
    view_details: "View Details",
    contact_landlord: "Contact Landlord",
    close: "Close",
    usp_title: "Rent without a 'fiador'",
    usp_description: "We exclusively list properties from landlords who welcome foreigners and locals without requiring a co-signer, making your move to Medellin smoother.",
    list_your_property_title: "List Your Property with NoFiador.com",
    list_your_property_subtitle: "Reach thousands of foreigners and locals looking for a home in Medellin. No co-signer required for tenants means more potential renters for you.",
    listing_fee: "One-time listing fee: $9.99 USD",
    pay_with_paypal: "Pay with PayPal",
    payment_success_title: "Payment Successful!",
    payment_success_message: "Your property is now listed on NoFiador.com. You will be contacted by interested tenants directly.",
    back_to_browsing: "Back to Browsing",
    all_rights_reserved: "All rights reserved.",
    login: "Log In",
    signup: "Sign Up",
    logout: "Log Out",
    profile: "Profile",
    email: "Email",
    password: "Password",
    landlord: "Landlord",
    renter: "Renter",
    i_am_a: "I am a...",
    login_to_account: "Log in to your account",
    create_account: "Create an account",
    dont_have_account: "Don't have an account?",
    already_have_account: "Already have an account?",
    login_failed: "Login failed. Please check your credentials.",
    signup_failed: "An account with this email already exists.",
    signup_failed_login_instead: "An account with this email already exists. Please log in instead.",
    signup_success: "Success! Please check your email for a verification link.",
    my_listings: "My Listings",
    my_saved_properties: "My Saved Properties",
    welcome_back: "Welcome back",
    no_listings_yet: "You haven't listed any properties yet.",
    no_saved_properties: "You haven't saved any properties yet. Click the heart icon on a listing to save it!",
    save: "Save",
    saved: "Saved",
    login_to_list: "Please log in as a landlord to list a property.",
    filter_by_neighborhood: "Filter by neighborhood",
    all_neighborhoods: "All Neighborhoods",
    sort_by_price: "Sort by price",
    price_low_to_high: "Price: Low to High",
    price_high_to_low: "Price: High to Low",
    next_step: "Next Step",
    back_step: "Back",
    publish_listing: "Publish Listing",
    update_listing: "Update Listing",
    step_1_title: "Step 1: Basic Information",
    step_2_title: "Step 2: Property Details",
    step_3_title: "Step 3: Photos",
    step_4_title: "Step 4: Review & Pay",
    title_en: "Title (English)",
    title_es: "Title (Spanish)",
    price_cpo: "Price (COP)",
    neighborhood: "Neighborhood",
    select_neighborhood: "Select a neighborhood",
    description_en: "Description (English)",
    description_es: "Description (Spanish)",
    photo_urls: "Photo URLs",
    photo_urls_placeholder: "Paste image URLs, separated by commas",
    photo_preview: "Photo Preview",
    edit: "Edit",
    delete: "Delete",
    delete_confirm_title: "Are you sure?",
    delete_confirm_message: "Are you sure you want to delete this listing? This action cannot be undone.",
    cancel: "Cancel",
    confirm_delete: "Yes, Delete",
    editing_property: "Editing Property",
    creating_property: "Creating New Property",
    create_account_to_message: "Create an account to send a message",
    signup_to_message: "Sign Up to Message",
    view_full_page: "View Full Page",
    edit_profile: "Edit Profile",
    settings: "Settings",
    contact_name: "Contact Name",
    contact_phone: "Contact Phone",
    save_changes: "Save Changes",
    profile_updated: "Profile updated successfully!",
    profile_update_error: "Failed to update profile.",
    no_properties_found_title: "No Properties Found Yet",
    no_properties_found_message: "Be the first to list a property on NoFiador.com! Are you a landlord?",
    list_your_property_cta: "List Your Property",
    step_3_subtitle: "Upload high-quality images of your property.",
    upload_photos: "Upload Photos",
    upload_prompt: "Click to select files, or drag and drop",
    upload_limit: "Up to 20 images. PNG, JPG supported.",
    remove_image: "Remove",
    uploading_images: "Uploading images...",
    error_uploading_images: "Error uploading images. Please try again.",
    paypal_error: "A PayPal error occurred. Please try again.",
    payment_processing: "Processing payment...",
    developer_note_title: "Developer Note",
    developer_note_paypal: "This is a simulated payment for testing in this environment. The live PayPal button will function on a standard web host.",
    simulate_payment_and_publish: "Simulate Payment & Publish",
    error_title: "Error",
    youtube_video_link: "YouTube Video Link",
    video_tour: "Video Tour",
    review_changes_and_update: "Review your changes below. When you are ready, click 'Update Listing' to save them.",
    updating: "Updating...",
    messages: "Messages",
    my_messages: "My Messages",
    send: "Send",
    type_your_message: "Type your message...",
    no_conversations: "You have no conversations yet.",
    select_conversation: "Select a conversation to start chatting.",
    message_sent: "Message sent!",
    message_failed: "Failed to send message.",
    start_conversation_prompt: "Send your first message to the landlord about this property.",
    login_to_contact: "Please log in to contact the landlord.",
    this_is_your_listing: "This is one of your listings.",
    login_to_message_cta: "Log In to Message",
  },
  es: {
    site_name: "NoFiador.com",
    site_slogan: "Tu hogar en Medellín, sin fiador.",
    browse_properties: "Ver Propiedades",
    list_property: "Publicar Propiedad",
    language: "Idioma",
    price_per_month: "/mes",
    bedrooms: "Habitaciones",
    bathrooms: "Baños",
    area: "m²",
    view_details: "Ver Detalles",
    contact_landlord: "Contactar al Propietario",
    close: "Cerrar",
    usp_title: "Alquila sin fiador",
    usp_description: "Listamos exclusivamente propiedades de arrendadores que aceptan extranjeros y locales sin requerir un fiador, facilitando tu mudanza a Medellín.",
    list_your_property_title: "Publica Tu Propiedad en NoFiador.com",
    list_your_property_subtitle: "Llega a miles de extranjeros y locales que buscan un hogar en Medellín. No requerir fiador para los inquilinos significa más potenciales arrendatarios para ti.",
    listing_fee: "Tarifa única por publicación: $9.99 USD",
    pay_with_paypal: "Pagar con PayPal",
    payment_success_title: "¡Pago Exitoso!",
    payment_success_message: "Tu propiedad ha sido publicada en NoFiador.com. Los inquilinos interesados se pondrán en contacto contigo directamente.",
    back_to_browsing: "Volver a Explorar",
    all_rights_reserved: "Todos los derechos reservados.",
    login: "Iniciar Sesión",
    signup: "Registrarse",
    logout: "Cerrar Sesión",
    profile: "Perfil",
    email: "Correo Electrónico",
    password: "Contraseña",
    landlord: "Arrendador",
    renter: "Inquilino",
    i_am_a: "Soy un...",
    login_to_account: "Inicia sesión en tu cuenta",
    create_account: "Crea una cuenta",
    dont_have_account: "¿No tienes una cuenta?",
    already_have_account: "¿Ya tienes una cuenta?",
    login_failed: "Error de inicio de sesión. Por favor, verifica tus credenciales.",
    signup_failed: "Ya existe una cuenta con este correo electrónico.",
    signup_failed_login_instead: "Ya existe una cuenta con este correo. Por favor, inicia sesión.",
    signup_success: "¡Éxito! Por favor, revisa tu correo para verificar tu cuenta.",
    my_listings: "Mis Propiedades",
    my_saved_properties: "Mis Propiedades Guardadas",
    welcome_back: "Bienvenido/a de nuevo",
    no_listings_yet: "Aún no has publicado ninguna propiedad.",
    no_saved_properties: "¡No has guardado ninguna propiedad todavía! Haz clic en el icono del corazón en una publicación para guardarla.",
    save: "Guardar",
    saved: "Guardado",
    login_to_list: "Por favor, inicia sesión como arrendador para publicar una propiedad.",
    filter_by_neighborhood: "Filtrar por barrio",
    all_neighborhoods: "Todos los Barrios",
    sort_by_price: "Ordenar por precio",
    price_low_to_high: "Precio: Menor a Mayor",
    price_high_to_low: "Precio: Mayor a Mayor",
    next_step: "Siguiente Paso",
    back_step: "Atrás",
    publish_listing: "Publicar Propiedad",
    update_listing: "Actualizar Propiedad",
    step_1_title: "Paso 1: Información Básica",
    step_2_title: "Paso 2: Detalles de la Propiedad",
    step_3_title: "Paso 3: Fotos",
    step_4_title: "Paso 4: Revisar y Pagar",
    title_en: "Título (Inglés)",
    title_es: "Título (Español)",
    price_cpo: "Precio (COP)",
    neighborhood: "Barrio",
    select_neighborhood: "Selecciona un barrio",
    description_en: "Descripción (Inglés)",
    description_es: "Descripción (Español)",
    photo_urls: "URLs de las Fotos",
    photo_urls_placeholder: "Pega las URLs de las imágenes, separadas por comas",
    photo_preview: "Vista Previa de Fotos",
    edit: "Editar",
    delete: "Eliminar",
    delete_confirm_title: "¿Estás seguro?",
    delete_confirm_message: "¿Estás seguro de que quieres eliminar esta propiedad? Esta acción no se puede deshacer.",
    cancel: "Cancelar",
    confirm_delete: "Sí, Eliminar",
    editing_property: "Editando Propiedad",
    creating_property: "Creando Nueva Propiedad",
    create_account_to_message: "Crea una cuenta para enviar un mensaje",
    signup_to_message: "Regístrate para Enviar Mensaje",
    view_full_page: "Ver Página Completa",
    edit_profile: "Editar Perfil",
    settings: "Configuración",
    contact_name: "Nombre de Contacto",
    contact_phone: "Teléfono de Contacto",
    save_changes: "Guardar Cambios",
    profile_updated: "¡Perfil actualizado con éxito!",
    profile_update_error: "Error al actualizar el perfil.",
    no_properties_found_title: "Aún no se han encontrado propiedades",
    no_properties_found_message: "¡Sé el primero en publicar una propiedad en NoFiador.com! ¿Eres arrendador?",
    list_your_property_cta: "Publica tu Propiedad",
    step_3_subtitle: "Sube imágenes de alta calidad de tu propiedad.",
    upload_photos: "Subir Fotos",
    upload_prompt: "Haz clic para seleccionar archivos o arrástralos aquí",
    upload_limit: "Hasta 20 imágenes. PNG, JPG admitidos.",
    remove_image: "Quitar",
    uploading_images: "Subiendo imágenes...",
    error_uploading_images: "Error al subir las imágenes. Por favor, inténtalo de nuevo.",
    paypal_error: "Ocurrió un error con PayPal. Por favor, inténtalo de nuevo.",
    payment_processing: "Procesando pago...",
    developer_note_title: "Nota para Desarrolladores",
    developer_note_paypal: "Este es un pago simulado para pruebas en este entorno. El botón de PayPal en vivo funcionará en un alojamiento web estándar.",
    simulate_payment_and_publish: "Simular Pago y Publicar",
    error_title: "Error",
    youtube_video_link: "Enlace de Video de YouTube",
    video_tour: "Tour en Video",
    review_changes_and_update: "Revisa tus cambios a continuación. Cuando estés listo, haz clic en 'Actualizar Propiedad' para guardarlos.",
    updating: "Actualizando...",
    messages: "Mensajes",
    my_messages: "Mis Mensajes",
    send: "Enviar",
    type_your_message: "Escribe tu mensaje...",
    no_conversations: "Aún no tienes conversaciones.",
    select_conversation: "Selecciona una conversación para empezar a chatear.",
    message_sent: "¡Mensaje enviado!",
    message_failed: "Error al enviar el mensaje.",
    start_conversation_prompt: "Envía tu primer mensaje al arrendador sobre esta propiedad.",
    login_to_contact: "Por favor, inicia sesión para contactar al arrendador.",
    this_is_your_listing: "Esta es una de tus propiedades.",
    login_to_message_cta: "Inicia Sesión para Enviar Mensaje",
  },
};

export const neighborhoods = [
  "Belen",
  "Buenos Aires",
  "El Carmen",
  "El Poblado",
  "El Retiro",
  "Envigado",
  "Itagui",
  "Laureles",
  "Manila",
  "Palmas",
  "Rionegro",
  "Sabaneta",
].sort();